### ISSUE TITLE
Master tracker

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/paperclip#152]
- [ ] Layers
  - [ ] Can rename a layer
  - [ ] Wire up `add` button
    - [ ] add an atom
    - [ ] add a style mixin
    - [ ] add an element
    - [ ] add a text node
- [ ] Properties panel
  - [ ] Attributes
    - [ ] Ability to define literal attributes
    - [ ] ability to define reference
  - [ ] Logic input
    - [ ] Ability to 
- [ ] Style panel
  - [ ] ability to add style mixin
  - [ ] display decl overrides (Webflow style)
  - [ ] input type
    - [ ] attachment
    - [ ] color
    - [ ] special UI for vars
    - [ ] suggestion menu should feel like auto-complete
- [ ] Assets
  - [ ] Display all assets (img, svg)
- [ ] Developer tooling
  - [ ] NPM installation (+ postinstall. See ngrok for inspiration: https://github.com/bubenshchykov/ngrok)
